import { Platform, StyleSheet } from "react-native";
import { colors, fonts } from "../Consts";
import {
  BackgroundSecondary,
  Error,
  Primary,
  TextTertiary,
  TextTitle,
} from "../Colors";
import globalStyles, { scale } from "../globalStyles";
export default StyleSheet.create({
  touchableDeny: {
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Error,
    backgroundColor: Error,
    justifyContent: "center",
    alignItems: "center",
    width: "47.5%",
  },
  infos: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  image: {
    height: scale(56),
    width: scale(56),
    borderRadius: 8,
    marginRight: scale(16),
  },
  listItems: {
    fontSize: globalStyles.h1,
    color: globalStyles.gray,
  },
  info: {
    flex: 1,
    flexDirection: "column",
  },
  name: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "500",
    color: globalStyles.gray,
  },
  function: {
    fontSize: globalStyles.h2,
    lineHeight: 16,
    color: globalStyles.primary,
  },
  stats: {
    width: "100%",
    borderRadius: 16,
    backgroundColor: globalStyles.iceWhite,
    padding: scale(4),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    color: globalStyles.darkGray,
  },
  flex: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  stateValue: {
    color: globalStyles.gray,
    fontSize: globalStyles.h2,
  },
  request: {
    marginTop: 24,
    width: "100%",
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    lineHeight: 24,
    backgroundColor: globalStyles.primary,
  },
  requestText: {
    textAlign: "center",
    color: globalStyles.white,
  },
  card: {
    width: "90%",
    alignSelf: "center",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    overflow: "hidden",
    padding: 20,
    borderWidth: 2,
    backgroundColor: globalStyles.white,
  },
  container: {
    top: "3%",
    bottom: 0,
    left: 0,
    right: 0,
    margin: "auto",
    borderRadius: 10,
    padding: 20,
  },
  containerBanner: {
    backgroundColor: Primary,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    height: 45,
    alignItems: "center",
  },
  bannerText: {
    color: colors.white,
    fontFamily: fonts.uberMedium,
    fontSize: 12,
  },
  bannerMuted: {
    color: "#fff",
    fontFamily: fonts.uberMedium,
    fontSize: 12,
  },
  containerInput: {
    alignItems: "center",
    backgroundColor: colors.white,
    flexDirection: "row",
    height: 48,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
  },
  containerSquare: {
    alignItems: "center",
    flex: 2,
  },
  square: {
    backgroundColor: Primary,
    height: 8,
    width: 8,
    borderRadius: 10,
  },
  text: {
    color: colors.greyAbbey,
    flex: 8,
    fontFamily: fonts.uberMedium,
    fontSize: 20,
  },
  title: {
    color: TextTitle,
    fontFamily: fonts.uberMedium,
    fontSize: 16,
    fontWeight: "bold",
  },
  containerIcon: {
    alignItems: "center",
    borderLeftColor: colors.greyMercury,
    borderLeftWidth: 1,
    flex: 2,
  },
  touchable: {
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Primary,
    backgroundColor: Primary,
    justifyContent: "center",
    alignItems: "center",
    width: "47.5%",
  },
  containerPending: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    margin: "auto",
    borderRadius: 10,
    padding: 20,
    top: "3%",
  },
  containerCard: {
    backgroundColor: colors.green,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },

  bannerMuted: {
    color: colors.white,
    fontFamily: fonts.uberMedium,
    fontSize: 14,

    borderRadius: 10,
    backgroundColor: Primary,
    borderColor: Primary,
    borderWidth: 2,
  },
  containerInput: {
    alignItems: "center",
    backgroundColor: colors.white,
    flexDirection: "row",
    height: 48,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
  },
  containerSquare: {
    alignItems: "center",
    flex: 1,
  },
  square: {
    backgroundColor: colors.black,
    height: 8,
    width: 8,
  },
  text: {
    color: colors.greyAbbey,
    flex: 2,
    fontFamily: fonts.uberMedium,
    fontSize: 19,
    paddingLeft: 10,
  },
  detalhes: {
    color: TextTertiary,
    fontFamily: fonts.uberMedium,
    fontSize: 16,
    fontWeight: "bold",
    paddingHorizontal: 15,
  },
  detalhesB: {
    color: TextTertiary,
    fontFamily: fonts.uberMedium,
    fontSize: 16,

    paddingHorizontal: 15,
  },
  containerIcon: {
    alignItems: "center",
    borderLeftColor: colors.greyMercury,
    borderLeftWidth: 1,
    borderRadius: 1,
    flex: 2,
    marginBottom: 1,
  },
  touchabletext: {
    color: BackgroundSecondary,
    fontWeight: "bold",
    fontSize: scale(14),
  },
  title: {
    color: TextTitle,
    fontFamily: fonts.uberMedium,
    fontSize: 16,
    fontWeight: "bold",
  },
  containerIcon: {
    alignItems: "center",
    borderLeftColor: colors.greyMercury,
    borderLeftWidth: 1,
    flex: 1,
  },
});
